Feat/core 2
PoCInnovation/ai-social-interaction pull request #1
Opened 2024-07-22 16:01 UTC by laiheau

# Description

Please provide a detailed description of what was done in this PR.

## Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

## Breaking changes

Please complete this section if any breaking changes have been made, otherwise delete it.

## Checklist

- [ ] I have assigned this PR to myself
- [ ] I have added at least 1 reviewer
- [ ] I have tested this code
- [ ] I have added sufficient documentation in the code

## Additional comments

Please post additional comments in this section if you have them, otherwise delete it.

2024-07-23 08:08 UTC, MatthiasvonRakowski commented on source/client/client.py
YOu have to put everythong in a function or class

2024-07-23 08:10 UTC, ramosleandre commented on source/client/memory.py
You need to also put the code in a function or class

2024-07-23 08:11 UTC, MatthiasvonRakowski commented on source/server/core.py
Put your global variable in a dataclass

2024-07-23 08:18 UTC, MatthiasvonRakowski requested changes
Check comments

2024-07-23 08:18 UTC, MatthiasvonRakowski commented on source/client/client.py
You have to put your global variable in a @ dataclass

2024-07-23 08:18 UTC, MatthiasvonRakowski commented on source/server/server.py
Put your global variable in a dataclass and you have to put any line in a class or function

2024-07-23 08:18 UTC, MatthiasvonRakowski commented on source/server/server.py
server must have a class

2024-07-23 08:18 UTC, MatthiasvonRakowski commented on source/client/client.py
client must have a class

2024-07-23 08:18 UTC, MatthiasvonRakowski commented on source/server/core.py
core must be a class

2024-07-23 08:18 UTC, ramosleandre requested changes
check the comments :)

2024-07-29 10:06 UTC, pierrelissope approved these changes

2024-07-29 10:29 UTC, LixiosDelios approved these changes

2024-09-15 14:35 UTC, merged